DROP TABLE IF EXISTS trade_record CASCADE;
DROP TABLE IF EXISTS product_inventory CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS sale CASCADE;
DROP TABLE IF EXISTS purchase CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS warehouse CASCADE;
DROP TABLE IF EXISTS product CASCADE;

CREATE TABLE IF NOT EXISTS app_user(
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS supplier(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL,
  metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS customer(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL,
  metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase(
  id SERIAL PRIMARY KEY,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  supplier INT NOT NULL REFERENCES supplier(id) ON DELETE CASCADE,
  app_user INT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS sale(
  id SERIAL PRIMARY KEY,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  customer INT NOT NULL REFERENCES customer(id) ON DELETE CASCADE,
  app_user INT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS product(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  purchase_price DECIMAL(10, 2) NOT NULL,
  sale_price DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS trade_record(
  id SERIAL PRIMARY KEY,
  product INT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
  quantity INT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  purchase INT REFERENCES purchase(id) ON DELETE CASCADE,
  sale INT REFERENCES sale(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS warehouse(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS product_inventory(
  id SERIAL PRIMARY KEY,
  product INT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
  quantity INT NOT NULL,
  warehouse INT NOT NULL REFERENCES warehouse(id) ON DELETE CASCADE
);
