DROP TABLE IF EXISTS TRADE_RECORD CASCADE;
DROP TABLE IF EXISTS PRODUCT_INVENTORY CASCADE;
DROP TABLE IF EXISTS INVENTORY CASCADE;
DROP TABLE IF EXISTS SALE CASCADE;
DROP TABLE IF EXISTS PURCHASE CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;
DROP TABLE IF EXISTS SUPPLIER CASCADE;
DROP TABLE IF EXISTS APP_USER CASCADE;
DROP TABLE IF EXISTS WAREHOUSE CASCADE;

CREATE TABLE IF NOT EXISTS APP_USER(
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SUPPLIER(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL,
  metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS CUSTOMER(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL,
  metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PURCHASE(
  id SERIAL PRIMARY KEY,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  supplier INT NOT NULL REFERENCES SUPPLIER(id),
  app_user INT NOT NULL REFERENCES APP_USER(id),
  status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS SALE(
  id SERIAL PRIMARY KEY,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  customer INT NOT NULL REFERENCES CUSTOMER(id),
  app_user INT NOT NULL REFERENCES APP_USER(id),
  status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  purchasePrice DECIMAL(10, 2) NOT NULL,
  salePrice DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRADE_RECORD(
  id SERIAL PRIMARY KEY,
  product INT NOT NULL REFERENCES PRODUCT(id),
  quantity INT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  purchase INT REFERENCES PURCHASE(id),
  sale INT REFERENCES SALE(id)
);

CREATE TABLE IF NOT EXISTS WAREHOUSE(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT_INVENTORY(
  id SERIAL PRIMARY KEY,
  product INT NOT NULL REFERENCES PRODUCT(id),
  quantity INT NOT NULL,
  warehouse INT NOT NULL REFERENCES WAREHOUSE(id)
);
