DROP TABLE IF EXISTS TradeRecord CASCADE;
DROP TABLE IF EXISTS ProductInventory CASCADE;
DROP TABLE IF EXISTS Inventory CASCADE;
DROP TABLE IF EXISTS Sale CASCADE;
DROP TABLE IF EXISTS Purchase CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Supplier CASCADE;
DROP TABLE IF EXISTS AppUser CASCADE;
DROP TABLE IF EXISTS Warehouse CASCADE;

CREATE TABLE IF NOT EXISTS AppUser(
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Supplier(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL,
  metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Customer(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL,
  metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Purchase(
  id SERIAL PRIMARY KEY,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  supplier INT NOT NULL REFERENCES Supplier(id),
  appUser INT NOT NULL REFERENCES AppUser(id),
  status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Sale(
  id SERIAL PRIMARY KEY,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  customer INT NOT NULL REFERENCES Customer(id),
  appUser INT NOT NULL REFERENCES AppUser(id),
  status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Product(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  purchasePrice DECIMAL(10, 2) NOT NULL,
  salePrice DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS TradeRecord(
  id SERIAL PRIMARY KEY,
  product INT NOT NULL REFERENCES Product(id),
  quantity INT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  purchase INT REFERENCES Purchase(id),
  sale INT REFERENCES Sale(id)
);

CREATE TABLE IF NOT EXISTS Warehouse(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ProductInventory(
  id SERIAL PRIMARY KEY,
  product INT NOT NULL REFERENCES Product(id),
  quantity INT NOT NULL,
  warehouse INT NOT NULL REFERENCES Warehouse(id)
);
