DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS SUPPLIER CASCADE;
DROP TABLE IF EXISTS PURCHASE CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;
DROP TABLE IF EXISTS SALES CASCADE;
DROP TABLE IF EXISTS WAREHOUSE CASCADE;
DROP TABLE IF EXISTS CATEGORY CASCADE;
DROP TABLE IF EXISTS PRODUCT CASCADE;
DROP TABLE IF EXISTS INVENTORY CASCADE;
DROP TABLE IF EXISTS TRADERECORD CASCADE;

CREATE TABLE IF NOT EXISTS USERS(
  userId SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SUPPLIER(
  supplierId SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PURCHASE(
  purchaseId SERIAL PRIMARY KEY,
  timestamp TEXT NOT NULL,
  supplierId INT NOT NULL,
  userId INT NOT NULL,
  tradeRecord TEXT NOT NULL,
  FOREIGN KEY (supplierId) REFERENCES SUPPLIER (supplierId) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (userId) REFERENCES USERS (userId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS CUSTOMER(
  customerId SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  metadata TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SALES(
  saleId SERIAL PRIMARY KEY,
  timestamp TEXT NOT NULL,
  customerId INT NOT NULL,
  userId INT NOT NULL,
  tradeRecord TEXT NOT NULL,
  FOREIGN KEY (customerId) REFERENCES CUSTOMER (customerId) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (userId) REFERENCES USERS (userId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS WAREHOUSE(
  warehouseId SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORY(
  categoryId SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS PRODUCT(
  productId SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  categoryId INT NOT NULL,
  description TEXT NOT NULL,
  purchasePrice TEXT NOT NULL,
  salePrice TEXT NOT NULL,
  FOREIGN KEY (categoryId) REFERENCES CATEGORY (categoryId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS INVENTORY(
 inventoryId SERIAL PRIMARY KEY,
 productId INT NOT NULL,
 quantity TEXT NOT NULL,
 warehouseId INT NOT NULL,
 FOREIGN KEY (warehouseId) REFERENCES WAREHOUSE (warehouseId) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (productId) REFERENCES PRODUCT (productId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS TRADERECORD(
  tradeRecordId SERIAL PRIMARY KEY,
  productId INT NOT NULL,
  quantity TEXT NOT NULL,
  price TEXT NOT NULL,
  purchaseId INT NOT NULL,
  saleId INT NOT NULL,
  FOREIGN KEY (productId) REFERENCES PRODUCT (productId) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (purchaseId) REFERENCES PURCHASE (purchaseId) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (saleId) REFERENCES SALES (saleId) ON DELETE CASCADE ON UPDATE CASCADE
);
