name: Node.js CI
on: [push]


jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x', '16.x', '18.x']
    

    steps:
    - name: Checkout Repository
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      working-directory: ./backend
      run: npm install
    - name: Run Tests
      run: npm run test-windows