name: Test Case Workflow

# Define when this workflow should run
on: push

# Define the jobs to be executed in this workflow
jobs:
  # Define the first job named "runner-job"
  runner-job:
    # Define the operating system for the job
    runs-on: ubuntu-latest

    # Define services that are required for the job
    services:
      # Define a PostgreSQL service
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    # Define the steps to be executed in the job
    steps:
      # Step to check out the code repository
      - name: Check out repository code
        uses: actions/checkout@v4
        
      # Step to set up Node.js runtime
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the version of Node.js

      # Step to install project dependencies
      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      # Step to connect to PostgreSQL and run tests
      - name: Run unittests
        working-directory: ./backend
        run: echo "test"
        env:
          DB_HOST: localhost
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_NAME: postgres
